== Domain

In this chapter we describe the building blocks of this application's domain.

=== Entities

The basic definition of an entity is: all objects which have an identity.
In our domain we use the following entities:

* User
* Player
* Team
* Game

==== User [[user-entity]]

A user is an authenticated person using our application.
This entity is created for each visitor of our application which completes authentication via OIDC identity provider.
We request the https://developer.okta.com/blog/2017/07/25/oidc-primer-part-1#whats-a-scope[profile and email scopes].
Thus, the entity has the following structure:

[source,json5]
----
{
  "id": "05bed545-1e18-4bf3-9f21-59237311f938",
  "email": "tichu.master@gmail.com",
  "name": "Tichu Master",
  "givenName": "Tichu",
  "familyName": "Master",
  "picture": "www.my-awesome-profile-picture.com",
  "createdAt": "2020-12-31 06:23:17"
}
----

==== Player [[player-entity]]

A user is participant of a game tracked by our application.
This entity is created for anonymous participants of a Tichu game.
All users are also players (but this is not modelled via inheritance).

[source,json5]
----
{
  "id": "0a5f6ea3-cf08-4dbd-9ea3-174502c4e4d1",
  "name": "Tichu Master",
  "createdAt": "2020-12-31 06:23:17"
}
----

==== Team [[team-entity]]

A team is a collection of exactly two players.

[source,json5]
----
{
  "id": "71a0b577-8f64-412c-8da6-835eb88b77e0",
  "name": "The name of the team",
  "firstPlayer": "094667f2-c967-476a-933d-1106ba61af51",
  "secondPlayer": "8329001b-591e-4496-96ca-c71a331c29f8",
}
----

==== Game [[game-entity]]

A game is a container for all information related to exactly one Tichu game.

[source,json5]
----
{
  "id": "3466b1bc-821c-42f6-9f83-1d29cb58699e",
  "createdBy": "094667f2-c967-476a-933d-1106ba61af51",
  "joinCode": "5f52cd8c",
  "teams": [ {}, {} ],
  "rounds": [ {}, {}, {}, ],
  "finishedAt": "2020-12-31 06:23:17"
}
----

=== Value Objects

==== Round [[round-value-object]]

A round is a container for all information related to one Tichu round.

[source,json5]
----
{
  "roundNumber": 1,
  "cardPoints": [
    {
      "71a0b577-8f64-412c-8da6-835eb88b77e0":  50,
      "6c260b37-de23-4d6f-bb3b-c0854e0ace17": 50
    }
  ],
  "ranks": {
    "094667f2-c967-476a-933d-1106ba61af51": 1,
    "8329001b-591e-4496-96ca-c71a331c29f8": 2,
    "d0dbf509-c942-40bd-a6a1-d01b912d2615": 3,
    "bf60d572-2cda-4bb7-8ff1-d6e383cf63b7": 4
  },
  "tichus": {
    "094667f2-c967-476a-933d-1106ba61af51": -1,
    "8329001b-591e-4496-96ca-c71a331c29f8": 100,
    "d0dbf509-c942-40bd-a6a1-d01b912d2615": -200,
    "bf60d572-2cda-4bb7-8ff1-d6e383cf63b7": -100
  }
}
----

==== CardPoints [[card-points-value-object]]

CardPoints represent the points a team achieved via the cards it won in one Tichu round.

[source,json5]
----
{
  "teamId": "71a0b577-8f64-412c-8da6-835eb88b77e0",
  "value": 15
}
----

=== Aggregates

=== Domain Events

A domain object that defines an event which is relevant to the application.

==== LoggedIn [[logged-in-event]]

[source,json5]
----
{
    "userId": "05bed545-1e18-4bf3-9f21-59237311f938",
    "name": "Tichu Master"
}
----

==== CreateGameEvent [[create-game-event]]

[source,json5]
----
{
    "userId": "05bed545-1e18-4bf3-9f21-59237311f938"
}
----

==== CreatedGame [[created-game-event]]

[source,json5]
----
{
    "gameId": "05bed545-1e18-4bf3-9f21-59237311f938",
    "joindCode": "5f52cd8c",
    "teamIds": [
      "71a0b577-8f64-412c-8da6-835eb88b77e0",
      "d6c7fddc-a8ba-4509-95e2-27b428ba21b4"
    ]
}
----

==== AddPlayer [[add-player-event]]

[source,json5]
----
{
    "teamId": "71a0b577-8f64-412c-8da6-835eb88b77e0",
    "name": "Another Tichu Master"
}
----

==== AddedPlayer [[added-player-event]]

[source,json5]
----
{
    "teams": {
        "teamId": "",
        "name": "",
        "players": [
          "094667f2-c967-476a-933d-1106ba61af51",
          "8329001b-591e-4496-96ca-c71a331c29f8"
        ]
    }
}
----

==== JoinGame [[join-game-event]]

Input:
JoinGame - user id - join code

[source,json5]
----
{
    "userId": "05bed545-1e18-4bf3-9f21-59237311f938",
    "joinCode": "5f52cd8c"
}
----

==== NavigateToAddPlayer [[navigate-to-add-player-event]]

[source,json5]
----
{
  // no body
}
----

=== Services

=== Repositories

'''
