== Domain

In this chapter we describe the building blocks of this application's domain.

=== Entities

The basic definition of an entity is: all object which have an identity.
In our domain we use the following entities:

* User
* Player
* Team
* Game
* Round

==== User [[user-entity]]

A user is an authenticated person using our application.
This entity is created for each visitor of our application which completes authentication via OIDC identity provider.
We request the https://developer.okta.com/blog/2017/07/25/oidc-primer-part-1#whats-a-scope[profile and email scopes].
Thus, the entity has the following structure:

[source,json5]
----
{
  "id": "05bed545-1e18-4bf3-9f21-59237311f938",
  "email": "tichu.master@gmail.com",
  "name": "Tichu Master",
  "picture": "www.my-awesome-profile-picture.com",
  "givenName": "Tichu",
  "familyName": "Master",
  "createdAt": "2020-12-31 06:23:17"
}
----

==== Player [[player-entity]]

A user is participant of a game tracked by our application.
This entity is created for anonymous participants of Tichu.
All users are also players.

[source,json5]
----
{
  "id": "0a5f6ea3-cf08-4dbd-9ea3-174502c4e4d1",
  "userId": "05bed545-1e18-4bf3-9f21-59237311f938",
  "name": "Tichu Master",
  "picture": "www.my-awesome-profile-picture.com",
  "createdAt": "2020-12-31 06:23:17"
}
----

==== Team [[team-entity]]

A team is a collection of exactly two players.

[source,json5]
----
{
  "id": "71a0b577-8f64-412c-8da6-835eb88b77e0",
  "players": [
    "094667f2-c967-476a-933d-1106ba61af51",
    "8329001b-591e-4496-96ca-c71a331c29f8"
  ],
  "createdAt": "2020-12-31 06:23:17"
}
----

==== Game [[game-entity]]

A game is a container for all information related to exactly one Tichu game.

[source,json5]
----
{
  "id": "3466b1bc-821c-42f6-9f83-1d29cb58699e",
  "joinCode": "5f52cd8c",
  "teams": [
    "71a0b577-8f64-412c-8da6-835eb88b77e0",
    "d6c7fddc-a8ba-4509-95e2-27b428ba21b4"
  ],
  "createdAt": "2020-12-31 06:23:17",
  "finishedAt": "2020-12-31 06:23:17"
}
----

==== Round [[round-entity]]

A game is a container for all information related to exactly one Tichu game.

[source,json5]
----
{
  "id": "3466b1bc-821c-42f6-9f83-1d29cb58699e",
  "gameId": "3466b1bc-821c-42f6-9f83-1d29cb58699e",
  "intermediateResults": [
    "3466b1bc-821c-42f6-9f83-1d29cb58699e",
    "b83fcd91-2fda-4a18-b6ab-a7603ddfe992"
  ],
  "createdAt": "2020-12-31 06:23:17",
}
----

==== Intermediate Result [[intermediate-result-entity]]

The result of one round of a Tichu game.

[source,json5]
----
{
  "id": "43d8d992-a254-41e9-aa7f-a7e2936863a8",
  "roundId": "3466b1bc-821c-42f6-9f83-1d29cb58699e",
  "points": [
    {
      "teamId": "71a0b577-8f64-412c-8da6-835eb88b77e0",
      "value": 85
    },
    {
      "teamId": "d6c7fddc-a8ba-4509-95e2-27b428ba21b4",
      "value": 15
    }
  ],
  "tichus" : [
    {
      "playerId": "094667f2-c967-476a-933d-1106ba61af51",
      "successful": true
    },
    {
      "playerId": "8329001b-591e-4496-96ca-c71a331c29f8",
      "successful": false
    }
  ],
  "grandTichus" : [
    {
      "playerId": "094667f2-c967-476a-933d-1106ba61af51",
      "successful": true
    },
    {
      "playerId": "8329001b-591e-4496-96ca-c71a331c29f8",
      "successful": false
    }
  ],
  "createdAt": "2020-12-31 06:23:17"
}
----

=== Value Objects

=== Aggregates

=== Domain Events

A domain object that defines an event which is relevant to the application.

==== LoggedIn [[logged-in-event]]

[source,json5]
----
{
    "userId": "05bed545-1e18-4bf3-9f21-59237311f938",
    "name": "Tichu Master"
}
----

==== CreateGame [[create-game-event]]

[source,json5]
----
{
    "userId": "05bed545-1e18-4bf3-9f21-59237311f938"
}
----

==== CreatedGame [[created-game-event]]

[source,json5]
----
{
    "gameId": "05bed545-1e18-4bf3-9f21-59237311f938",
    "joindCode": "5f52cd8c",
    "teamIds": [
      "71a0b577-8f64-412c-8da6-835eb88b77e0",
      "d6c7fddc-a8ba-4509-95e2-27b428ba21b4"
    ]
}
----

==== AddPlayer [[add-player-event]]

[source,json5]
----
{
    "teamId": "71a0b577-8f64-412c-8da6-835eb88b77e0",
    "name": "Another Tichu Master"
}
----

==== AddedPlayer [[added-player-event]]

[source,json5]
----
{
    "teams": {
        "teamId": "",
        "name": "",
        "players": [
          "094667f2-c967-476a-933d-1106ba61af51",
          "8329001b-591e-4496-96ca-c71a331c29f8"
        ]
    }
}
----

==== JoinGame [[join-game-event]]

Input:
JoinGame
- user id
- join code

[source,json5]
----
{
    "userId": "05bed545-1e18-4bf3-9f21-59237311f938",
    "joinCode": "5f52cd8c"
}
----

==== NavigateToAddPlayer [[navigate-to-add-player-event]]

[source,json5]
----
{
  // no body
}
----

=== Services

=== Repositories

---
